(cl:defpackage first-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "BIRTHDAY"
   "<BIRTHDAY-REQUEST>"
   "BIRTHDAY-REQUEST"
   "<BIRTHDAY-RESPONSE>"
   "BIRTHDAY-RESPONSE"
  ))

