; Auto-generated. Do not edit!


(cl:in-package first-msg)


;//! \htmlinclude CakeGoal.msg.html

(cl:defclass <CakeGoal> (roslisp-msg-protocol:ros-message)
  ((num_cakes
    :reader num_cakes
    :initarg :num_cakes
    :type cl:integer
    :initform 0))
)

(cl:defclass CakeGoal (<CakeGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CakeGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CakeGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name first-msg:<CakeGoal> is deprecated: use first-msg:CakeGoal instead.")))

(cl:ensure-generic-function 'num_cakes-val :lambda-list '(m))
(cl:defmethod num_cakes-val ((m <CakeGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader first-msg:num_cakes-val is deprecated.  Use first-msg:num_cakes instead.")
  (num_cakes m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CakeGoal>) ostream)
  "Serializes a message object of type '<CakeGoal>"
  (cl:let* ((signed (cl:slot-value msg 'num_cakes)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CakeGoal>) istream)
  "Deserializes a message object of type '<CakeGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'num_cakes) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CakeGoal>)))
  "Returns string type for a message object of type '<CakeGoal>"
  "first/CakeGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CakeGoal)))
  "Returns string type for a message object of type 'CakeGoal"
  "first/CakeGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CakeGoal>)))
  "Returns md5sum for a message object of type '<CakeGoal>"
  "6d3e30b2ed75c520b8f2ca1010c57ae6")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CakeGoal)))
  "Returns md5sum for a message object of type 'CakeGoal"
  "6d3e30b2ed75c520b8f2ca1010c57ae6")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CakeGoal>)))
  "Returns full string definition for message of type '<CakeGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int64 num_cakes~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CakeGoal)))
  "Returns full string definition for message of type 'CakeGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int64 num_cakes~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CakeGoal>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CakeGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'CakeGoal
    (cl:cons ':num_cakes (num_cakes msg))
))
