; Auto-generated. Do not edit!


(cl:in-package first-msg)


;//! \htmlinclude CakeResult.msg.html

(cl:defclass <CakeResult> (roslisp-msg-protocol:ros-message)
  ((message
    :reader message
    :initarg :message
    :type cl:string
    :initform ""))
)

(cl:defclass CakeResult (<CakeResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CakeResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CakeResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name first-msg:<CakeResult> is deprecated: use first-msg:CakeResult instead.")))

(cl:ensure-generic-function 'message-val :lambda-list '(m))
(cl:defmethod message-val ((m <CakeResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader first-msg:message-val is deprecated.  Use first-msg:message instead.")
  (message m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CakeResult>) ostream)
  "Serializes a message object of type '<CakeResult>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'message))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'message))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CakeResult>) istream)
  "Deserializes a message object of type '<CakeResult>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'message) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'message) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CakeResult>)))
  "Returns string type for a message object of type '<CakeResult>"
  "first/CakeResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CakeResult)))
  "Returns string type for a message object of type 'CakeResult"
  "first/CakeResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CakeResult>)))
  "Returns md5sum for a message object of type '<CakeResult>"
  "5f003d6bcc824cbd51361d66d8e4f76c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CakeResult)))
  "Returns md5sum for a message object of type 'CakeResult"
  "5f003d6bcc824cbd51361d66d8e4f76c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CakeResult>)))
  "Returns full string definition for message of type '<CakeResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CakeResult)))
  "Returns full string definition for message of type 'CakeResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CakeResult>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'message))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CakeResult>))
  "Converts a ROS message object to a list"
  (cl:list 'CakeResult
    (cl:cons ':message (message msg))
))
