; Auto-generated. Do not edit!


(cl:in-package first-msg)


;//! \htmlinclude CakeFeedback.msg.html

(cl:defclass <CakeFeedback> (roslisp-msg-protocol:ros-message)
  ((cake_baked
    :reader cake_baked
    :initarg :cake_baked
    :type cl:integer
    :initform 0))
)

(cl:defclass CakeFeedback (<CakeFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CakeFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CakeFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name first-msg:<CakeFeedback> is deprecated: use first-msg:CakeFeedback instead.")))

(cl:ensure-generic-function 'cake_baked-val :lambda-list '(m))
(cl:defmethod cake_baked-val ((m <CakeFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader first-msg:cake_baked-val is deprecated.  Use first-msg:cake_baked instead.")
  (cake_baked m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CakeFeedback>) ostream)
  "Serializes a message object of type '<CakeFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'cake_baked)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CakeFeedback>) istream)
  "Deserializes a message object of type '<CakeFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'cake_baked) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CakeFeedback>)))
  "Returns string type for a message object of type '<CakeFeedback>"
  "first/CakeFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CakeFeedback)))
  "Returns string type for a message object of type 'CakeFeedback"
  "first/CakeFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CakeFeedback>)))
  "Returns md5sum for a message object of type '<CakeFeedback>"
  "d07d0961a6435407e0940bb5c723c2f2")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CakeFeedback)))
  "Returns md5sum for a message object of type 'CakeFeedback"
  "d07d0961a6435407e0940bb5c723c2f2")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CakeFeedback>)))
  "Returns full string definition for message of type '<CakeFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int64 cake_baked~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CakeFeedback)))
  "Returns full string definition for message of type 'CakeFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int64 cake_baked~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CakeFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CakeFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CakeFeedback
    (cl:cons ':cake_baked (cake_baked msg))
))
