; Auto-generated. Do not edit!


(cl:in-package first-msg)


;//! \htmlinclude CounterGoal.msg.html

(cl:defclass <CounterGoal> (roslisp-msg-protocol:ros-message)
  ((Limit
    :reader Limit
    :initarg :Limit
    :type cl:integer
    :initform 0))
)

(cl:defclass CounterGoal (<CounterGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CounterGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CounterGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name first-msg:<CounterGoal> is deprecated: use first-msg:CounterGoal instead.")))

(cl:ensure-generic-function 'Limit-val :lambda-list '(m))
(cl:defmethod Limit-val ((m <CounterGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader first-msg:Limit-val is deprecated.  Use first-msg:Limit instead.")
  (Limit m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CounterGoal>) ostream)
  "Serializes a message object of type '<CounterGoal>"
  (cl:let* ((signed (cl:slot-value msg 'Limit)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CounterGoal>) istream)
  "Deserializes a message object of type '<CounterGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'Limit) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CounterGoal>)))
  "Returns string type for a message object of type '<CounterGoal>"
  "first/CounterGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CounterGoal)))
  "Returns string type for a message object of type 'CounterGoal"
  "first/CounterGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CounterGoal>)))
  "Returns md5sum for a message object of type '<CounterGoal>"
  "f74e2cd829d807680604a2a671162f6d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CounterGoal)))
  "Returns md5sum for a message object of type 'CounterGoal"
  "f74e2cd829d807680604a2a671162f6d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CounterGoal>)))
  "Returns full string definition for message of type '<CounterGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int64 Limit~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CounterGoal)))
  "Returns full string definition for message of type 'CounterGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int64 Limit~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CounterGoal>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CounterGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'CounterGoal
    (cl:cons ':Limit (Limit msg))
))
