; Auto-generated. Do not edit!


(cl:in-package first-msg)


;//! \htmlinclude CounterResult.msg.html

(cl:defclass <CounterResult> (roslisp-msg-protocol:ros-message)
  ((Limit_Reached
    :reader Limit_Reached
    :initarg :Limit_Reached
    :type cl:integer
    :initform 0))
)

(cl:defclass CounterResult (<CounterResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CounterResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CounterResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name first-msg:<CounterResult> is deprecated: use first-msg:CounterResult instead.")))

(cl:ensure-generic-function 'Limit_Reached-val :lambda-list '(m))
(cl:defmethod Limit_Reached-val ((m <CounterResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader first-msg:Limit_Reached-val is deprecated.  Use first-msg:Limit_Reached instead.")
  (Limit_Reached m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CounterResult>) ostream)
  "Serializes a message object of type '<CounterResult>"
  (cl:let* ((signed (cl:slot-value msg 'Limit_Reached)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CounterResult>) istream)
  "Deserializes a message object of type '<CounterResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'Limit_Reached) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CounterResult>)))
  "Returns string type for a message object of type '<CounterResult>"
  "first/CounterResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CounterResult)))
  "Returns string type for a message object of type 'CounterResult"
  "first/CounterResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CounterResult>)))
  "Returns md5sum for a message object of type '<CounterResult>"
  "b5f0aff541c8b82c0617bf0b4d5d2ab2")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CounterResult)))
  "Returns md5sum for a message object of type 'CounterResult"
  "b5f0aff541c8b82c0617bf0b4d5d2ab2")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CounterResult>)))
  "Returns full string definition for message of type '<CounterResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int64 Limit_Reached~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CounterResult)))
  "Returns full string definition for message of type 'CounterResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int64 Limit_Reached~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CounterResult>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CounterResult>))
  "Converts a ROS message object to a list"
  (cl:list 'CounterResult
    (cl:cons ':Limit_Reached (Limit_Reached msg))
))
