; Auto-generated. Do not edit!


(cl:in-package first-msg)


;//! \htmlinclude CounterFeedback.msg.html

(cl:defclass <CounterFeedback> (roslisp-msg-protocol:ros-message)
  ((current
    :reader current
    :initarg :current
    :type cl:integer
    :initform 0))
)

(cl:defclass CounterFeedback (<CounterFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CounterFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CounterFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name first-msg:<CounterFeedback> is deprecated: use first-msg:CounterFeedback instead.")))

(cl:ensure-generic-function 'current-val :lambda-list '(m))
(cl:defmethod current-val ((m <CounterFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader first-msg:current-val is deprecated.  Use first-msg:current instead.")
  (current m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CounterFeedback>) ostream)
  "Serializes a message object of type '<CounterFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'current)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CounterFeedback>) istream)
  "Deserializes a message object of type '<CounterFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'current) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CounterFeedback>)))
  "Returns string type for a message object of type '<CounterFeedback>"
  "first/CounterFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CounterFeedback)))
  "Returns string type for a message object of type 'CounterFeedback"
  "first/CounterFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CounterFeedback>)))
  "Returns md5sum for a message object of type '<CounterFeedback>"
  "0b6da3dca7a4642ded212e4b180c47f0")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CounterFeedback)))
  "Returns md5sum for a message object of type 'CounterFeedback"
  "0b6da3dca7a4642ded212e4b180c47f0")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CounterFeedback>)))
  "Returns full string definition for message of type '<CounterFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int64 current~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CounterFeedback)))
  "Returns full string definition for message of type 'CounterFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int64 current~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CounterFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CounterFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CounterFeedback
    (cl:cons ':current (current msg))
))
