// Auto-generated. Do not edit!

// (in-package first.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class CounterResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.Limit_Reached = null;
    }
    else {
      if (initObj.hasOwnProperty('Limit_Reached')) {
        this.Limit_Reached = initObj.Limit_Reached
      }
      else {
        this.Limit_Reached = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CounterResult
    // Serialize message field [Limit_Reached]
    bufferOffset = _serializer.int64(obj.Limit_Reached, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CounterResult
    let len;
    let data = new CounterResult(null);
    // Deserialize message field [Limit_Reached]
    data.Limit_Reached = _deserializer.int64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'first/CounterResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'b5f0aff541c8b82c0617bf0b4d5d2ab2';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int64 Limit_Reached
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CounterResult(null);
    if (msg.Limit_Reached !== undefined) {
      resolved.Limit_Reached = msg.Limit_Reached;
    }
    else {
      resolved.Limit_Reached = 0
    }

    return resolved;
    }
};

module.exports = CounterResult;
