// Generated by gencpp from file first/BirthdayRequest.msg
// DO NOT EDIT!


#ifndef FIRST_MESSAGE_BIRTHDAYREQUEST_H
#define FIRST_MESSAGE_BIRTHDAYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace first
{
template <class ContainerAllocator>
struct BirthdayRequest_
{
  typedef BirthdayRequest_<ContainerAllocator> Type;

  BirthdayRequest_()
    : age(0)  {
    }
  BirthdayRequest_(const ContainerAllocator& _alloc)
    : age(0)  {
  (void)_alloc;
    }



   typedef int64_t _age_type;
  _age_type age;





  typedef boost::shared_ptr< ::first::BirthdayRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::first::BirthdayRequest_<ContainerAllocator> const> ConstPtr;

}; // struct BirthdayRequest_

typedef ::first::BirthdayRequest_<std::allocator<void> > BirthdayRequest;

typedef boost::shared_ptr< ::first::BirthdayRequest > BirthdayRequestPtr;
typedef boost::shared_ptr< ::first::BirthdayRequest const> BirthdayRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::first::BirthdayRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::first::BirthdayRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::first::BirthdayRequest_<ContainerAllocator1> & lhs, const ::first::BirthdayRequest_<ContainerAllocator2> & rhs)
{
  return lhs.age == rhs.age;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::first::BirthdayRequest_<ContainerAllocator1> & lhs, const ::first::BirthdayRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace first

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::first::BirthdayRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::first::BirthdayRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first::BirthdayRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first::BirthdayRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first::BirthdayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first::BirthdayRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::first::BirthdayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad4e277089388e2eeb41d6a7004f5cc0";
  }

  static const char* value(const ::first::BirthdayRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad4e277089388e2eULL;
  static const uint64_t static_value2 = 0xeb41d6a7004f5cc0ULL;
};

template<class ContainerAllocator>
struct DataType< ::first::BirthdayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "first/BirthdayRequest";
  }

  static const char* value(const ::first::BirthdayRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::first::BirthdayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 age\n"
;
  }

  static const char* value(const ::first::BirthdayRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::first::BirthdayRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.age);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BirthdayRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::first::BirthdayRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::first::BirthdayRequest_<ContainerAllocator>& v)
  {
    s << indent << "age: ";
    Printer<int64_t>::stream(s, indent + "  ", v.age);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIRST_MESSAGE_BIRTHDAYREQUEST_H
