// Generated by gencpp from file first/CakeFeedback.msg
// DO NOT EDIT!


#ifndef FIRST_MESSAGE_CAKEFEEDBACK_H
#define FIRST_MESSAGE_CAKEFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace first
{
template <class ContainerAllocator>
struct CakeFeedback_
{
  typedef CakeFeedback_<ContainerAllocator> Type;

  CakeFeedback_()
    : cake_baked(0)  {
    }
  CakeFeedback_(const ContainerAllocator& _alloc)
    : cake_baked(0)  {
  (void)_alloc;
    }



   typedef int64_t _cake_baked_type;
  _cake_baked_type cake_baked;





  typedef boost::shared_ptr< ::first::CakeFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::first::CakeFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct CakeFeedback_

typedef ::first::CakeFeedback_<std::allocator<void> > CakeFeedback;

typedef boost::shared_ptr< ::first::CakeFeedback > CakeFeedbackPtr;
typedef boost::shared_ptr< ::first::CakeFeedback const> CakeFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::first::CakeFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::first::CakeFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::first::CakeFeedback_<ContainerAllocator1> & lhs, const ::first::CakeFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.cake_baked == rhs.cake_baked;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::first::CakeFeedback_<ContainerAllocator1> & lhs, const ::first::CakeFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace first

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::first::CakeFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::first::CakeFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first::CakeFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first::CakeFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first::CakeFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first::CakeFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::first::CakeFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d07d0961a6435407e0940bb5c723c2f2";
  }

  static const char* value(const ::first::CakeFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd07d0961a6435407ULL;
  static const uint64_t static_value2 = 0xe0940bb5c723c2f2ULL;
};

template<class ContainerAllocator>
struct DataType< ::first::CakeFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "first/CakeFeedback";
  }

  static const char* value(const ::first::CakeFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::first::CakeFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int64 cake_baked\n"
;
  }

  static const char* value(const ::first::CakeFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::first::CakeFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cake_baked);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CakeFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::first::CakeFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::first::CakeFeedback_<ContainerAllocator>& v)
  {
    s << indent << "cake_baked: ";
    Printer<int64_t>::stream(s, indent + "  ", v.cake_baked);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIRST_MESSAGE_CAKEFEEDBACK_H
