// Generated by gencpp from file first/CakeGoal.msg
// DO NOT EDIT!


#ifndef FIRST_MESSAGE_CAKEGOAL_H
#define FIRST_MESSAGE_CAKEGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace first
{
template <class ContainerAllocator>
struct CakeGoal_
{
  typedef CakeGoal_<ContainerAllocator> Type;

  CakeGoal_()
    : num_cakes(0)  {
    }
  CakeGoal_(const ContainerAllocator& _alloc)
    : num_cakes(0)  {
  (void)_alloc;
    }



   typedef int64_t _num_cakes_type;
  _num_cakes_type num_cakes;





  typedef boost::shared_ptr< ::first::CakeGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::first::CakeGoal_<ContainerAllocator> const> ConstPtr;

}; // struct CakeGoal_

typedef ::first::CakeGoal_<std::allocator<void> > CakeGoal;

typedef boost::shared_ptr< ::first::CakeGoal > CakeGoalPtr;
typedef boost::shared_ptr< ::first::CakeGoal const> CakeGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::first::CakeGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::first::CakeGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::first::CakeGoal_<ContainerAllocator1> & lhs, const ::first::CakeGoal_<ContainerAllocator2> & rhs)
{
  return lhs.num_cakes == rhs.num_cakes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::first::CakeGoal_<ContainerAllocator1> & lhs, const ::first::CakeGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace first

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::first::CakeGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::first::CakeGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first::CakeGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first::CakeGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first::CakeGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first::CakeGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::first::CakeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6d3e30b2ed75c520b8f2ca1010c57ae6";
  }

  static const char* value(const ::first::CakeGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6d3e30b2ed75c520ULL;
  static const uint64_t static_value2 = 0xb8f2ca1010c57ae6ULL;
};

template<class ContainerAllocator>
struct DataType< ::first::CakeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "first/CakeGoal";
  }

  static const char* value(const ::first::CakeGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::first::CakeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int64 num_cakes\n"
;
  }

  static const char* value(const ::first::CakeGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::first::CakeGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num_cakes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CakeGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::first::CakeGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::first::CakeGoal_<ContainerAllocator>& v)
  {
    s << indent << "num_cakes: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num_cakes);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIRST_MESSAGE_CAKEGOAL_H
