// Generated by gencpp from file first/CounterFeedback.msg
// DO NOT EDIT!


#ifndef FIRST_MESSAGE_COUNTERFEEDBACK_H
#define FIRST_MESSAGE_COUNTERFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace first
{
template <class ContainerAllocator>
struct CounterFeedback_
{
  typedef CounterFeedback_<ContainerAllocator> Type;

  CounterFeedback_()
    : current(0)  {
    }
  CounterFeedback_(const ContainerAllocator& _alloc)
    : current(0)  {
  (void)_alloc;
    }



   typedef int64_t _current_type;
  _current_type current;





  typedef boost::shared_ptr< ::first::CounterFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::first::CounterFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct CounterFeedback_

typedef ::first::CounterFeedback_<std::allocator<void> > CounterFeedback;

typedef boost::shared_ptr< ::first::CounterFeedback > CounterFeedbackPtr;
typedef boost::shared_ptr< ::first::CounterFeedback const> CounterFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::first::CounterFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::first::CounterFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::first::CounterFeedback_<ContainerAllocator1> & lhs, const ::first::CounterFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.current == rhs.current;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::first::CounterFeedback_<ContainerAllocator1> & lhs, const ::first::CounterFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace first

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::first::CounterFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::first::CounterFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first::CounterFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first::CounterFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first::CounterFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first::CounterFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::first::CounterFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b6da3dca7a4642ded212e4b180c47f0";
  }

  static const char* value(const ::first::CounterFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b6da3dca7a4642dULL;
  static const uint64_t static_value2 = 0xed212e4b180c47f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::first::CounterFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "first/CounterFeedback";
  }

  static const char* value(const ::first::CounterFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::first::CounterFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int64 current\n"
;
  }

  static const char* value(const ::first::CounterFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::first::CounterFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CounterFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::first::CounterFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::first::CounterFeedback_<ContainerAllocator>& v)
  {
    s << indent << "current: ";
    Printer<int64_t>::stream(s, indent + "  ", v.current);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIRST_MESSAGE_COUNTERFEEDBACK_H
