// Generated by gencpp from file first/MonthRequest.msg
// DO NOT EDIT!


#ifndef FIRST_MESSAGE_MONTHREQUEST_H
#define FIRST_MESSAGE_MONTHREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace first
{
template <class ContainerAllocator>
struct MonthRequest_
{
  typedef MonthRequest_<ContainerAllocator> Type;

  MonthRequest_()
    : Age(0)  {
    }
  MonthRequest_(const ContainerAllocator& _alloc)
    : Age(0)  {
  (void)_alloc;
    }



   typedef int64_t _Age_type;
  _Age_type Age;





  typedef boost::shared_ptr< ::first::MonthRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::first::MonthRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MonthRequest_

typedef ::first::MonthRequest_<std::allocator<void> > MonthRequest;

typedef boost::shared_ptr< ::first::MonthRequest > MonthRequestPtr;
typedef boost::shared_ptr< ::first::MonthRequest const> MonthRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::first::MonthRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::first::MonthRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::first::MonthRequest_<ContainerAllocator1> & lhs, const ::first::MonthRequest_<ContainerAllocator2> & rhs)
{
  return lhs.Age == rhs.Age;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::first::MonthRequest_<ContainerAllocator1> & lhs, const ::first::MonthRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace first

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::first::MonthRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::first::MonthRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first::MonthRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first::MonthRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first::MonthRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first::MonthRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::first::MonthRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c292748aa9831817ccbcf68f7d33f1d6";
  }

  static const char* value(const ::first::MonthRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc292748aa9831817ULL;
  static const uint64_t static_value2 = 0xccbcf68f7d33f1d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::first::MonthRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "first/MonthRequest";
  }

  static const char* value(const ::first::MonthRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::first::MonthRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 Age\n"
;
  }

  static const char* value(const ::first::MonthRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::first::MonthRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Age);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MonthRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::first::MonthRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::first::MonthRequest_<ContainerAllocator>& v)
  {
    s << indent << "Age: ";
    Printer<int64_t>::stream(s, indent + "  ", v.Age);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIRST_MESSAGE_MONTHREQUEST_H
