// Generated by gencpp from file first/Months.msg
// DO NOT EDIT!


#ifndef FIRST_MESSAGE_MONTHS_H
#define FIRST_MESSAGE_MONTHS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace first
{
template <class ContainerAllocator>
struct Months_
{
  typedef Months_<ContainerAllocator> Type;

  Months_()
    : name()
    , number(0)  {
    }
  Months_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , number(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef int64_t _number_type;
  _number_type number;





  typedef boost::shared_ptr< ::first::Months_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::first::Months_<ContainerAllocator> const> ConstPtr;

}; // struct Months_

typedef ::first::Months_<std::allocator<void> > Months;

typedef boost::shared_ptr< ::first::Months > MonthsPtr;
typedef boost::shared_ptr< ::first::Months const> MonthsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::first::Months_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::first::Months_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::first::Months_<ContainerAllocator1> & lhs, const ::first::Months_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.number == rhs.number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::first::Months_<ContainerAllocator1> & lhs, const ::first::Months_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace first

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::first::Months_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::first::Months_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first::Months_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first::Months_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first::Months_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first::Months_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::first::Months_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b4c0f13b3f4a45ae2d788a4843c5f00";
  }

  static const char* value(const ::first::Months_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b4c0f13b3f4a45aULL;
  static const uint64_t static_value2 = 0xe2d788a4843c5f00ULL;
};

template<class ContainerAllocator>
struct DataType< ::first::Months_<ContainerAllocator> >
{
  static const char* value()
  {
    return "first/Months";
  }

  static const char* value(const ::first::Months_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::first::Months_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"int64 number\n"
;
  }

  static const char* value(const ::first::Months_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::first::Months_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Months_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::first::Months_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::first::Months_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "number: ";
    Printer<int64_t>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIRST_MESSAGE_MONTHS_H
